### ISSUE TITLE
NAT and Routing Configuration: List of supported resources

### ISSUE THREAD

**Issue by dinsharm** [bluecough/terraform-provider-ciscofdm#2]
Do you have a list of supported resources? I want to  configure NAT  and routing using terraform, is that supported?

I know terraform Cisco ASA provider supports static route configuration, i tried the same way but looks like i am not using the  correct syntax.

https://registry.terraform.io/providers/CiscoDevNet/ciscoasa/latest/docs/resources/static_route

I tried the following syntax for static route:

resource "ciscofdm_static_route" "ipv4_static_route" {

  interface = "outside"

  network   = "0.0.0.0/0"

  gateway   = "198.18.128.1"

}

and got the following error:

 Error: Invalid resource type
│ 
│   on main.tf line 249, in resource "ciscofdm_static_route" "ipv4_static_route":
│  249: resource "ciscofdm_static_route" "ipv4_static_route" {
│ 
│ The provider hashicorp/ciscofdm does not support resource type "ciscofdm_static_route".

Please  advise

Thanks,
Dinkar

**Comment by bluecough** [comment]
Dinkar,

Sorry it is not supported at this time. The ASA provider is an official release.

**Comment by dinsharm** [comment]
> Dinkar,
> 
> Sorry it is not supported at this time. The ASA provider is an official release.

So is  this something which will be supported in the future? I do see FMC provider as well, is that officially supported?

https://registry.terraform.io/providers/CiscoDevNet/fmc/latest

Do you have a list of resources for ASA provider?  For example i don't  see any resource for configuring NAT in ASA. is that supported? if not how can i make an official request for support?
